spring.application.name=ecommerce-backend
spring.datasource.url=jdbc:postgresql://localhost:5445/ecommerce
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.app.jwtSecret=VGhpc0lzQVNlY3JldEtleUZvckpXVFQxMjM0NTY3ODkw
spring.app.jwtExpirationMs=86400000
spring.ecom.app.jwtCookieName=jwt
#show the queries
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Disable stack trace in error responses
server.error.include-stacktrace=never
server.error.include-message=never